# Generated by Django 4.0.4 on 2022-05-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(to='core.category'),
        ),
        migrations.AddField(
            model_name='institution',
            name='type_of_institution',
            field=models.CharField(choices=[('F', 'Foundation'), ('NG', 'Non-governmental'), ('LC', 'Local collection')], default='F', max_length=2),
        ),
    ]
